language: python
services: mongodb
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.2"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="Django>=1.5"
install:
  - pip install $DJANGO --use-mirrors
script: python setup.py nosetests
